version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/workspace
    steps:
      - run:
          name: Install Ansible
          command: sudo apt-add-repository ppa:ansible/ansible ; sudo apt update ; sudo apt install ansible
      
      - run:
          name: Install packer to build
          command: sudo wget https://releases.hashicorp.com/packer/1.4.4/packer_1.4.4_linux_amd64.zip -O /opt/packer.zip

      - run:
          name: Unzip Packer
          command: sudo unzip /opt/packer.zip -d /opt

      - run: 
          name: give executeable access
          command: sudo chmod +x /opt/packer 

      - run:
          name: docker login
          command: echo `echo $DOCKER_PASSWORD | base64 -d` | docker login -u $DOCKER_USERNAME --password-stdin

      - checkout

      - run:
          name: validate python ansible
          command: /opt/packer validate ./python-alpine.json
      - run:
          name: Validate centos remaster
          command: /opt/packer validate ./centos-remaster.json
  
      - run:
          name: Build docker images
          command: /opt/packer build ./python-alpine.json
      
      - run:
          name: Build docker images 2
          command: /opt/packer build ./centos-remaster.json

      - run:
          name: List docker images
          command: docker images -a 

workflows:
  version: 2
  build:
    jobs:
      - build