version: 2
jobs:
  provisioning-vm:
    machine: true
    working_directory: ~/workspace
    steps:
      - run:
          name: Install Ansible
          command: sudo apt-add-repository ppa:ansible/ansible ; sudo apt update ; sudo apt install ansible
      
      - run:
          name: Install packer to build
          command: wget https://releases.hashicorp.com/packer/1.4.4/packer_1.4.4_linux_amd64.zip

      - run:
          name: Unzip Packer
          command: unzip ./packer_1.4.4_linux_amd64.zip

      - run: 
          name: give executeable access
          command: chmod +x ./packer ; sudo mv ./packer /opt/packer
      
  packer-validate:
    machine: true
    working_directory: ~/workspace
    steps:
      - checkout
      - run:
          name: validate python ansible
          command: /opt/packer validate ./python-alpine.json
      - run:
          name: Validate centos remaster
          command: /opt/packer validate ./centos-remaster.json

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - provisioning-vm
      - packer-validate
          requires: provisioning-vm