version: 2
jobs:
  build:
    machine: true
    working_directory: ~/workspace
    steps:
      - run:
          name: Install Ansible
          command: sudo apt-add-repository ppa:ansible/ansible ; sudo apt update ; sudo apt install ansible
      
      - run:
          name: Install packer to build
          command: sudo wget https://releases.hashicorp.com/packer/1.4.4/packer_1.4.4_linux_amd64.zip -O /opt/packer.zip

      - run:
          name: Unzip Packer
          command: unzip /opt/packer.zip

      - run: 
          name: give executeable access
          command: sudo chmod +x /opt/packer 
      
      - checkout
      - run:
          name: validate python ansible
          command: /opt/packer validate ./python-alpine.json
      - run:
          name: Validate centos remaster
          command: /opt/packer validate ./centos-remaster.json

workflows:
  version: 2
  build:
    jobs:
      - build