version: 2
jobs:
  validate:
    docker:
      - image: hashicorp/packer:1.1.1
    working_directory: ~/packer
    steps:
      - checkout
      - run:
          name: validate 
          command: packer validate ./python-alpine.json
      - run:
          name: Validate snowflake
          command: packer validate ./centos-remaster.json

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - validate