version: 2
jobs:
  validate:
    machine: true
    working_directory: ~/workspace
    steps:
      
      - run:
          name: Install Ansible
          command: apt install ansible
      
      - run:
          name: Install packer to build
          command: wget https://releases.hashicorp.com/packer/1.4.4/packer_1.4.4_linux_amd64.zip

      - run:
          name: Unzip Packer
          command: unzip ./packer_1.4.4_linux_amd64.zip

      - run: 
          name: give executeable access
          command: chmod +x ./packer
      
      - checkout
      
      - run:
          name: validate 
          command: packer validate ./python-alpine.json
      - run:
          name: Validate snowflake
          command: packer validate ./centos-remaster.json

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - validate