version: 2
jobs:
  provisioning:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/workspace
    steps:
      - run:
          name: Install Ansible
          command: sudo apt-add-repository ppa:ansible/ansible ; sudo apt update ; sudo apt install ansible
      
      - run:
          name: Install packer to build
          command: sudo wget https://releases.hashicorp.com/packer/1.4.4/packer_1.4.4_linux_amd64.zip -O /opt/packer.zip

      - run:
          name: Unzip Packer
          command: sudo unzip /opt/packer.zip -d /opt
      - run:
          name: Listing packer
          command: ls /opt
   
  
      - run:
          name: Listing packer 2
          command: ls ${pwd} 
  test: 
    machine: true
    steps: 
      - run: 
          name: give executeable access
          command: sudo chmod +x /opt/packer 
      - run:
          name: docker login
          command: docker login -u $DOCKER_USERNAME -p `echo $DOCKER_PASSWORD | base64 -d`
      - checkout
      - run:
          name: validate python ansible
          command: /opt/packer validate ./python-alpine.json
      - run:
          name: Validate centos remaster
          command: /opt/packer validate ./centos-remaster.json
  build: 
    machine: true
    steps: 
      - run:
          name: Build docker images
          command: /opt/packer build ./python-alpine.json
      
      - run:
          name: Build docker images 2
          command: /opt/packer build ./centos-remaster.json

workflows:
  version: 2
  provisioning-test-build:
    jobs:
      - provisioning
      - test: 
          requires: 
            - provisioning
      - build: 
          requires:
            - test